1. Implementasi Normalisasi

In [2]:
def norm_data(data):
    '''
    Melakukan normalisasi data.

    Parameters:
    data (list) : Data yang akan dinormalisasi

    Returns:
    data (list) : Data hasil normalisasi
    
    '''
    data_max = max(data)
    data_min = min(data)
    data_len = len(data)

    for i in range(data_len):
        data[i] = (data[i] - data_min) / (data_max - data_min)

    return data

# Contoh Penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data)
print(n_data)


[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions (precision=6) # bulatkan 4 angkat koma
np.set_printoptions (suppress=True) # hilangkan nilai e

# Kita akan membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input
# dalam bentuk n-dimensional array
data = [
[100, 0.0001],
[50, 0.05],
[30, 0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli' )
print(data)

# Mendefinisikan obyek MinMaxScaler
scaler = MinMaxScaler ()
# Transformasikan data
scaled = scaler.fit_transform(data)
print('Data Normalisasi' )
print (scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


2. Implementasi Standarisasi

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions (precision=6) # bulatkan 4 angkat koma
np.set_printoptions (suppress=True) # hilangkan nilai e

# Kita akan membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input
# dalam bentuk n-dimensional array
data = [
[100, 0.0001],
[50, 0.05],
[30, 0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print ('Data Asli' )
print(data)

# Mendefinisikan obyek MinMaxScaler
scaler = StandardScaler ()
# Transformasikan data
scaled = scaler.fit_transform(data)
print ('Data Standarisasi' )
print (scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


3. Implementasi Ordinal Encoding

In [2]:
from sklearn.preprocessing import OrdinalEncoder

# Inisiasi obyek Ordinal Encoder
oe = OrdinalEncoder ()

# Definisikan data
# dalam bentuk 2d
data = [
['Politeknik Negeri Malang' ],
['Politeknik Elektronika Negeri Surabaya'],
['Politeknik Negeri Jakarata' ],
['Politeknik Negeri Semarang' ]
]

# Transformasi Ordinal Encoder
transform_oe = oe.fit_transform(data)

print('Data Asli' )
print(data)

print('Data Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


4. Implementasi One-Hot Encoding

In [4]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek Ordinal Encoder
ohe = OneHotEncoder ()

# Definisikan data
# dalam bentuk 2d
data = [
['Politeknik Negeri Malang'],
['Politeknik Elektronika Negeri Surabaya'],
['Politeknik Negeri Jakarata'],
['Politeknik Negeri Semarang']
]

# Transformasi Ordinal Encoder
transform_ohe = ohe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One-Hot Encoding' )
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


5. Implementasi Dummy Variable Encoding

In [5]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek Ordinal Encoder
de = OneHotEncoder (drop='first' )

# Definisikan data
# dalam bentuk 2d
data = [
['Politeknik Negeri Malang' ],
['Politeknik Elektronika Negeri Surabaya'],
['Politeknik Negeri Jakarata'],
['Politeknik Negeri Semarang' ]
]

# Transformasi Ordinal Encoder
transform_de = de.fit_transform(data)

print('Data Asli' )
print(data)

print('Data Transformasi One-Hot Encoding')
print (transform_de.toarray ( ) )

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
